library('RUnit')
source('URL Generator.R')
test.suite <- defineTestSuite("example",dirs = file.path("tests"),testFileRegexp = '^\\d+\\.R')
test.result <- runTestSuite(test.suite)
printTextProtocol(test.result)
